# Generated by Django 6.0.2 on 2026-03-11 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCounty',
            new_name='VisitedCounty',
        ),
        migrations.AlterUniqueTogether(
            name='visitedcounty',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
